//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipTo
    {
        public int ShipToId { get; set; }
        public int CustomerId { get; set; }
        public string ShipToAddress { get; set; }
        public string ShipToPhone { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
